name: bepl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - click=7.1.1=py_0
  - intel-openmp=2020.0=166
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - openssl=1.1.1g=h7b6447c_0
  - pip=20.0.2=py37_1
  - portaudio=19.6.0=h7b6447c_4
  - pyaudio=0.2.11=py37h7b6447c_2
  - python=3.7.7=hcf32534_0_cpython
  - readline=8.0=h7b6447c_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - audioread==2.1.8
    - cffi==1.14.0
    - decorator==4.4.2
    - ffmpeg-python==0.2.0
    - future==0.18.2
    - joblib==0.14.1
    - librosa==0.7.2
    - llvmlite==0.32.0
    - numba==0.49.0
    - pycparser==2.20
    - pygame==1.9.6
    - resampy==0.2.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - soundfile==0.10.3.post1

